name: Build and deploy Marp slides to username.github.io

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install marp-cli
        run: npm install -g @marp-team/marp-cli

      - name: Build slides to HTML and PDF
        run: |
          rm -rf out
          mkdir -p out
          # Build HTML (adjust theme path if needed)
          marp slides.md --theme themes/lioncity-finai.css -o out/index.html
          # Optional: build PDF
          marp slides.md --theme themes/lioncity-finai.css --pdf -o out/slides.pdf
          # Copy theme and assets into out/assets for predictable paths
          mkdir -p out/assets/css
          cp themes/lioncity-finai.css out/assets/css/lioncity-finai.css || true
          # If you have images/fonts in a folder, copy them too (adjust paths)
          if [ -d assets ]; then cp -r assets out/; fi

      - name: Deploy to username.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_repo: username/username.github.io
          publish_branch: main
