name: Build and deploy Marp slides to username.github.io

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install marp-cli
        run: npm install -g @marp-team/marp-cli

      - name: Build slides to HTML and PDF
        run: |
          rm -rf out
          mkdir -p out
          marp slides.md --theme ./lioncity-finai.css -o out/index.html
          marp slides.md --theme ./lioncity-finai.css --pdf -o out/slides.pdf || true
          mkdir -p out/assets/css
          cp lioncity-finai.css out/assets/css/lioncity-finai.css || true

      - name: Smoke test built HTML
        run: |
          if ! grep -q "Gold and Bitcoin as Inflation Hedges" out/index.html; then
            echo "Smoke test failed: expected title not found in out/index.html"
            exit 1
          fi

      - name: Deploy to username.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_repo: jojowibowo/jojowibowo.github.io
          publish_branch: main
